## Question 1 - Python 101

### Question 1.1

---
❓ Define a variable called **key_sentence** with the following sentence:
_"Learning Data Analytics at Le Wagon is amazing!"_

In [1]:
# Your code here
key_sentence= "Learning Data Analytics at Le Wagon is amazing!"
key_sentence

'Learning Data Analytics at Le Wagon is amazing!'

### Question 1.2

---
❓ Print the length of the sentence stored in the variable **key_sentence**.

In [2]:
# Your code here
print(len(key_sentence)) # running this code we got the lenght of the sentence: 47

47


## Question 2 - Data Sourcing and EDA with Pandas

The goal of this challenge is to analyze movies on IMDb. Some code cells are already implemented, you just need to **run** them. Some other cells need you to write some code.

Start the challenge by running the two following cells:

**Please guarantee that you have saved the *IMDb movies.csv* in the same folder as you have saved this document!** 

*If you store it in a different folder you will have to define the path within the **pd.read_csv()** function.*

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [4]:
imdb_movies = pd.read_csv('IMDb movies.csv', low_memory=False) # attending the DtypeWarning that we got, we added the argument ´low_memory=False´

In [5]:
imdb_movies.shape

(85855, 22)

---

Apply the following code to create a new DataFrame called **imdb_filtered** which filters the **imdb_movies** DataFrame to only include movies from the below listed countries and genres:

**Countries**:
   - USA
   - UK
   - India
   - France
   - China
   - Portugal


**Genres**:
   - Drama
   - Comedy
   - Thriller 
   - Horror

In [6]:
countries_to_keep = ['USA','UK','India','France','China','Portugal']

genres_to_keep = ['Drama','Comedy','Thriller','Horror']


imdb_filtered = imdb_movies[imdb_movies.country.isin(countries_to_keep)]

imdb_filtered = imdb_filtered[imdb_filtered.genre.isin(genres_to_keep)]

In [7]:
imdb_filtered.shape # checking the result and comparing with above one, we conclude that:
#the initial dataframe has 85855rows x 22 columns, and the filtered dataset has 10074 rows x 22columns

(10074, 22)

 **Always use the *imdb_filtered* DataFrame for answering the upcoming questions!**

### Question 2.1

---

❓ Display the 10 first rows of the **imdb_filtered** DataFrame (no need to sort)

In [8]:
# Your code here
imdb_filtered.head(10) # to check the first 10 rows of dataframe 
#REPLY QUESTION 2.1:

imdb_title_id                       title              original_title  \
17     tt0003167              Amore di madre            Home, Sweet Home   
28     tt0003973       A Florida Enchantment       A Florida Enchantment   
32     tt0004134                  Hypocrites                  Hypocrites   
34     tt0004181          Judith of Bethulia          Judith of Bethulia   
38     tt0004681      La madonnina del porto   Tess of the Storm Country   
39     tt0004707  Tillie's Punctured Romance  Tillie's Punctured Romance   
41     tt0004743           Uncle Tom's Cabin           Uncle Tom's Cabin   
48     tt0005060                      Carmen                      Carmen   
51     tt0005339                  La vampira            A Fool There Was   
52     tt0005402           The Golden Chance           The Golden Chance   

    year date_published   genre  duration country       language  \
17  1914     1914-05-17   Drama        55     USA        English   
28  1914     1916-09-04  Comedy        63     USA        English   
32  1915     1915-01-20   Drama        54     USA        English   
34  1914     1914-03-08   Drama        61     USA        English   
38  1914     1914-03-30   Drama        80     USA        English   
39  1914     1914-12-21  Comedy        82     USA  None, English   
41  1914     1914-08-10   Drama        54     USA            NaN   
48  1915     1915-10-31   Drama        59     USA        English   
51  1915     1915-01-12   Drama        67     USA        English   
52  1915     1915-12-30   Drama        74     USA        English   

                         director  ...  \
17                  D.W. Griffith  ...   
28                    Sidney Drew  ...   
32                     Lois Weber  ...   
34                  D.W. Griffith  ...   
38                Edwin S. Porter  ...   
39  Mack Sennett, Charles Bennett  ...   
41            William Robert Daly  ...   
48               Cecil B. DeMille  ...   
51                   Frank Powell  ...   
52               Cecil B. DeMille  ...   

                                               actors  \
17  Henry B. Walthall, Josephine Crowell, Lillian ...   
28  Sidney Drew, Edith Storey, Charles Kent, Mrs. ...   
32  Courtenay Foote, Myrtle Stedman, Herbert Stand...   
34  Blanche Sweet, Henry B. Walthall, Mae Marsh, R...   
38  Mary Pickford, Harold Lockwood, Olive Carey, D...   
39  Marie Dressler, Charles Chaplin, Mabel Normand...   
41  Sam Lucas, Walter Hitchcock, Hattie Delaro, Ma...   
48  Geraldine Farrar, Wallace Reid, Pedro de Cordo...   
51  Runa Hodges, Mabel Frenyear, Edward José, May ...   
52  Cleo Ridgely, Wallace Reid, Horace B. Carpente...   

                                          description avg_vote votes   budget  \
17  John Howard Payne at his most miserable point ...      5.8   187      NaN   
28  A young woman discovers a seed that can make w...      5.8   202      NaN   
32  The parallel stories of a modern preacher and ...      6.6   456      NaN   
34  A religious woman seeks to save her people fro...      6.1  1239  $ 40000   
38  A wealthy resident attempts to dispossess squa...      6.1   178  $ 10000   
39  A con man from the city dupes a wealthy countr...      6.3  3250  $ 50000   
41  A black and white silent film based on Harriet...      5.3   112      NaN   
48  In order to help her smuggler kinsmen, a sultr...      6.4   894  $ 23430   
51  A married diplomat falls hopelessly under the ...      5.8   783      NaN   
52  Mary Denby becomes a seamstress after her husb...      6.4   187  $ 18711   

    usa_gross_income worlwide_gross_income metascore reviews_from_users  \
17               NaN                   NaN       NaN                6.0   
28               NaN                   NaN       NaN                6.0   
32               NaN                   NaN       NaN               41.0   
34               NaN                   NaN       NaN               16.0   
38               NaN                   NaN       NaN       

### Question 2.2

---

❓How many rows and columns exist in the **imdb_filtered** DataFrame?

In [9]:
# Your code here
imdb_filtered.shape[0] # rows
imdb_filtered.shape[1] # columns
#reply QUESTION 2.2
print(f"In the 'imdb_filtered' DataFrame exists {imdb_filtered.shape[0]} rows and {imdb_filtered.shape[1]} columns.")

In the 'imdb_filtered' DataFrame exists 10074 rows and 22 columns.


### Question 2.3

---

❓Drop the columns in the *columns_to_drop* list below from the **imdb_filtered** DataFrame:

In [10]:
columns_to_drop = ['title', 'date_published', 'writer','actors','description','usa_gross_income',
                   'worlwide_gross_income','metascore','reviews_from_users','reviews_from_critics'] 

In [11]:
# Your code here
imdb_filtered.drop(columns_to_drop, axis=1, inplace=True) # THIS IS REPLY QUESITON 2.3
# to drop columns need to add axis=1
#also added inplace=True, to assign the changes to imdb_filtered again

In [12]:
imdb_filtered.shape # running this we can see that now we have less 10 columns. total 12 columns

(10074, 12)

In [13]:
imdb_filtered.head() #checking the columns with what we will work from now

imdb_title_id             original_title  year   genre  duration country  \
17     tt0003167           Home, Sweet Home  1914   Drama        55     USA   
28     tt0003973      A Florida Enchantment  1914  Comedy        63     USA   
32     tt0004134                 Hypocrites  1915   Drama        54     USA   
34     tt0004181         Judith of Bethulia  1914   Drama        61     USA   
38     tt0004681  Tess of the Storm Country  1914   Drama        80     USA   

   language         director               production_company  avg_vote  \
17  English    D.W. Griffith  Majestic Motion Picture Company       5.8   
28  English      Sidney Drew     Vitagraph Company of America       5.8   
32  English       Lois Weber      Hobart Bosworth Productions       6.6   
34  English    D.W. Griffith                 Biograph Company       6.1   
38  English  Edwin S. Porter      Famous Players Film Company       6.1   

    votes   budget  
17    187      NaN  
28    202      NaN  
32    456      NaN  
34   1239  $ 40000  
38    178  $ 10000

In [14]:
# additionaly let us to check more info, which can be useful ahead, during data inspection
imdb_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10074 entries, 17 to 85852
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   imdb_title_id       10074 non-null  object 
 1   original_title      10074 non-null  object 
 2   year                10074 non-null  object 
 3   genre               10074 non-null  object 
 4   duration            10074 non-null  int64  
 5   country             10074 non-null  object 
 6   language            9898 non-null   object 
 7   director            10061 non-null  object 
 8   production_company  9394 non-null   object 
 9   avg_vote            10074 non-null  float64
 10  votes               10074 non-null  int64  
 11  budget              2526 non-null   object 
dtypes: float64(1), int64(2), object(9)
memory usage: 1023.1+ KB


In [15]:
imdb_filtered.describe()

duration      avg_vote         votes
count  10074.00000  10074.000000  1.007400e+04
mean      97.21759      5.599940  4.205883e+03
std       20.86501      1.355902  3.736504e+04
min       45.00000      1.100000  9.900000e+01
25%       86.00000      4.700000  1.690000e+02
50%       93.00000      5.800000  3.280000e+02
75%      104.00000      6.600000  8.370000e+02
max      418.00000      9.700000  2.278845e+06

In [43]:
imdb_filtered[imdb_filtered.duplicated()]

Empty DataFrame
Columns: [imdb_title_id, original_title, year, genre, duration, country, language, director, production_company, avg_vote, votes, budget]
Index: []

First notes of this initial overview 
- our filtered dataset has 10074 entries and 12 columns;
- almost all column don't have missing values, except `budget`, `production_company` and `language`;
- `budget` column has a big qty of missing (NaN) values;
- `production_company` and `language` also have few missing (NaN) values;
- almost all column are formated as string (object type), except `duration`, `votes` and `avg_vote` which are already in numerical format (int or float) -  based on this information, we need to take special with:
    * `year` column, which despite contains datetime information is still not formated as datetime nor as numerical type - we may need to format this column with correct format.
    * `budget` column, which despite contains monetary information is still not formated as numerical type-  we may need to check if we have all values in same currency - as we have different countries we should have different currencies. Depending of our needs, we may need to convert all values to USD for the values could be compared), then we will need to take out the currency symbol and leave only the numerical information.
- regarding columns already in numerical type, we can see some statistics:
    * regarding `duration`: we have films between 45 min and 418min (~7h) and the mean is 97min (1h37min)
    * regarding `avg_votes`: we can see that the average votes are between range 1.10 - 9.7 and the mean is 5.6
- there is not any duplicated rows in the dataset


- we may need tot check ahead, some unique values of each column or check other kind of information in order to understand if there are some information that we will need to clean.

### Question 2.4

---

❓How many movies exist in total? Store the result in a variable called **total_movie_number**.

In [65]:
# Your code here
#reply QUESTION 2.4
total_movie_number=imdb_filtered.shape[0]
print(total_movie_number)
print(f"In total exists {total_movie_number} movies (excluding the duplicated rows for the same movie).")

10074
In total exists 10074 movies (excluding the duplicated rows for the same movie).


In [57]:
# For curiosity, not related with this question specifically
# we checked if we have movies with same name, and check an example
# even name is the same, it is expectable that year and company could be different (besides other info)

In [61]:
#List of duplicated original titles:
imdb_filtered[imdb_filtered.duplicated("original_title")].head(3)

imdb_title_id   original_title  year  genre  duration country language  \
1363     tt0023228  The Miracle Man  1932  Drama        85     USA  English   
1394     tt0023345  Poil de carotte  1932  Drama        91  France   French   
1637     tt0024405     Oliver Twist  1933  Drama        80     USA  English   

              director                        production_company  avg_vote  \
1363  Norman Z. McLeod                        Paramount Pictures       6.2   
1394   Julien Duvivier  Les Films Marcel Vandal et Charles Delac       7.3   
1637  William J. Cowen                 I.E. Chadwick Productions       4.9   

      votes budget  
1363    124    NaN  
1394    569    NaN  
1637    310    NaN

In [60]:
imdb_filtered[imdb_filtered.original_title.isin(["The Miracle Man"])]

imdb_title_id   original_title  year  genre  duration country language  \
168      tt0010466  The Miracle Man  1919  Drama        80     USA  English   
1363     tt0023228  The Miracle Man  1932  Drama        85     USA  English   

                 director           production_company  avg_vote  votes  \
168   George Loane Tucker  Mayflower Photoplay Company       6.6    145   
1363     Norman Z. McLeod           Paramount Pictures       6.2    124   

        budget  
168   $ 120000  
1363       NaN

In [64]:
#if we want to count the number of movies without duplicated we can count them as following way:|
movies_with_different_names=imdb_filtered["original_title"].nunique()

### Question 2.5

---

❓ What are the 10 movies with the hightest average vote? 

In [17]:
# Your code here
imdb_filtered.sort_values("avg_vote", ascending=False).head(10)
# checking the dateframe print on question 2.3 we could see the name of the column of  average vote to use here.
# we use "ascending=False", to filter the first 10 results, otherwise, we will need to filter the last 10 results

imdb_title_id                             original_title  year  \
84434     tt8571428                        Vaarthakal Ithuvare  2019   
58809     tt1508669                              Hopeful Notes  2010   
54166    tt11164090                        The Moving on Phase  2020   
28453     tt0111161                   The Shawshank Redemption  1994   
81109     tt6735740                           Love in Kilnerry  2019   
76069     tt4897596                                  Digbhayam  2019   
84623     tt8718580                                  Eghantham  2018   
54313    tt11280912              Maarjaara Oru Kalluvacha Nuna  2020   
52407    tt10127546  National Theatre Live: The Lehman Trilogy  2019   
53698    tt10867504                                        Fan  2019   

          genre  duration country   language                        director  \
84434    Comedy       121   India  Malayalam                      Manoj Nair   
58809     Drama        94     USA    English                  Valerio Zanoli   
54166    Comedy        85     USA    English                   Don Tjernagel   
28453     Drama       142     USA    English                  Frank Darabont   
81109    Comedy       100     USA    English  Daniel Keith, Snorri Sturluson   
76069  Thriller       107   India    Kannada                           Amith   
84623     Drama       125   India      Tamil                  Arsel Arumugam   
54313     Drama       142   India  Malayalam                   Raakesh Baala   
52407     Drama       223      UK        NaN                      Sam Mendes   
53698     Drama       145   India    Kannada         Balavalli Darshith Bhat   

              production_company  avg_vote    votes        budget  
84434       Lawson Entertainment       9.7      473           NaN  
58809               High Concept       9.7      669     $ 1500000  
54166                        NaN       9.5      172           NaN  
28453  Castle Rock Entertainment       9.3  2278845    $ 25000000  
81109           Archway Pictures       9.3     1239     $ 3000000  
76069        1234 Cine Creations       9.2      247  INR 12000000  
84623        Annai Tamil Cinemas       9.2      644           NaN  
54313    Mullappally Productions       9.2      347           NaN  
52407                        NaN       9.2      138           NaN  
53698                SLN Cinemas       9.2      879  INR 20000000

In [18]:
# reply QUESTION 2.5
print("The 10 movies with the hightest average vote are the following: \n")
imdb_filtered.sort_values('avg_vote', ascending=False).head(10)['original_title']



The 10 movies with the hightest average vote are the following: 



84434                          Vaarthakal Ithuvare
58809                                Hopeful Notes
54166                          The Moving on Phase
28453                     The Shawshank Redemption
81109                             Love in Kilnerry
76069                                    Digbhayam
84623                                    Eghantham
54313                Maarjaara Oru Kalluvacha Nuna
52407    National Theatre Live: The Lehman Trilogy
53698                                          Fan
Name: original_title, dtype: object

In [19]:
#alternative way to get this result is to use nlargest:
imdb_filtered.nlargest(10, 'avg_vote')['original_title']

58809                                Hopeful Notes
84434                          Vaarthakal Ithuvare
54166                          The Moving on Phase
28453                     The Shawshank Redemption
81109                             Love in Kilnerry
52407    National Theatre Live: The Lehman Trilogy
53698                                          Fan
54313                Maarjaara Oru Kalluvacha Nuna
76069                                    Digbhayam
84623                                    Eghantham
Name: original_title, dtype: object

### Question 2.6

---

❓ What are the 10 production companies with the most movies? Plot this with a Matplotlib barchart.

In [20]:
# Your code here
# reply QUESTION 2.5
print("The 10 production companies with the most movies are the following: \n")
imdb_filtered["production_company"].value_counts().head(10) #dropna=False - if we want to count NaN- if we use this we will see that we have many rows without production company information

The 10 production companies with the most movies are the following: 



Metro-Goldwyn-Mayer (MGM)    178
Warner Bros.                 132
Paramount Pictures           120
Columbia Pictures            105
Twentieth Century Fox         91
RKO Radio Pictures            68
Universal Pictures            66
The Rank Organisation         48
Canal+                        44
First National Pictures       28
Name: production_company, dtype: int64

In [21]:
imdb_filtered["production_company"].value_counts().head(10).plot(kind="bar", rot=80, alpha=0.55, title="The TOP 10 of production companies with the most movies") # added rot to slant a little the axes x label. and added alpha, to give some transparency to the the bar colors
plt.ylabel("Total of movies")
plt.show()

In [22]:
#in my opinion it will be better to use the following alternative with horizontal bars:
imdb_filtered["production_company"].value_counts().head(10).plot(kind="barh", alpha=0.55, title="The TOP 10 of production companies with the most movies") # added rot to slant a little the axes x label. and added alpha, to give some transparency to the the bar colors
plt.xlabel("Total of movies")
plt.show()

### Question 2.7

---

❓ Elaborate on the distribution of the average vote. Take advantage of the Seaborn Distplot to answer to this!

In [23]:
# Your code here
#sns.distplot(imdb_filtered['avg_vote']) #-> attending the warning, instead this distplot, 
#plt.show() #-> we will use histplot with following arguments, and result'll be the same
           
sns.histplot(imdb_filtered['avg_vote'],  kde=True, stat="density", linewidth=0)
plt.show()

Based on this histogram, we can conclude that:
* average vote has a normal distribution. 
* the most common average votes are around 6.


### Question 2.8

---

❓ What are the most common genres in each country? Elaborate and plot this with a Seaborn countplot.

In [24]:
# Your code here
sns.countplot(data=imdb_filtered, x="country", hue="genre")
plt.show()

Based on this graphic (and in bellow table), we can conclude that the genre Drama is the most common genre in all these 6 country.




In [25]:
# let us do pivot table to see the total of each genre per country
#we highlight in yellow color the maximum per row
imdb_filtered.pivot_table(index="country",columns="genre", aggfunc={'genre':len}, fill_value=0).style.highlight_max(color = 'yellow', axis = 1)

# we used as help for style: https://stackoverflow.com/questions/45606458/python-pandas-highlighting-maximum-value-in-column

In [26]:
# to find maximum values of every row we can do the following -> need to use the argument axis=1 for row 
#however we didn't find way to use this to change the style of pivot table:
max_row= imdb_filtered.pivot_table(index="country",columns="genre", aggfunc={'genre':len}, fill_value=0).max(axis=1)


### Question 2.9

---

❓ What is the influence of the country on the duration of the movies? Take advantage of a Seaborn violin or box plot to answer this. Elaborate.

In [27]:
# Your code here
sns.catplot(data=imdb_filtered, x='country', y='duration', kind="violin")
plt.show()

Checking this plot we can see we have outliers values which will make harder our analyze.
So we will slice our dataset to remove this outliers values.


Checking following calculations, we can see that we have only 18 rows with duration more than 180 min.
Attending total dataset has 10074, this 34 rows, are only 0,34%, so we will remove them from our analyze. and we will remake a the previous plot.

In [28]:
print(f"The number of rows with more than 200 of duraction is: {imdb_filtered[imdb_filtered['duration']>180].shape[0]}.")

print("This represent only: {:,.2f}% of total entries of our data set".format(34/10074*100))

The number of rows with more than 200 of duraction is: 34.
This represent only: 0.34% of total entries of our data set


In [29]:
imdb_slice_duration=imdb_filtered[imdb_filtered["duration"]<=180]
sns.set_style("whitegrid")#added grid to visualize better the realations among the contries plots.
sns.catplot(data=imdb_slice_duration, x='country', y='duration', kind="violin")
plt.show()

In [30]:
# following pivot table with mean duration per country is only to help on elaboration of conclusions:
imdb_filtered.pivot_table(index="country", values="duration") #mean is the default aggfunc

duration
country             
China     106.192308
France     96.329937
India     130.456039
Portugal  101.163934
UK         93.990764
USA        91.204925

In general way, we know that:
- Each plot has a white dot represents the median of duration of movie of each country.
- As thicker is the colored part of plot it means that there is higher probability to have one movie from that country with that value of durantion.


<br>
<br>

This way, checking this graphic we can see:
- The Indian movies are the one with biggest probability to have bigger duration (on table we see India has the bigger mean -around 130 min - and on plot we see the India's median duration is the highest one)
- The films from USA, France and UK are the one with  lower duration (in average duration between 91-96 min )
- The most quantity of films from USA, France and UK, are concentrated around their median durations. This is visible on plot because the shape of these distributions (extremely skinny on each end and wide/large in the middle) indicates the duration of movies from these countries are highly concentrated around the median.
- In Portugal, China and India, we have many movies with durations bigger and lower than the median duration of those countries. We can see this on plot,  because the the shape of distribution has thinner middle part and the colored part is more stretched.


- One other conclusion we still could take is about the maximum and minimum durations. If we check the first plot (before our decision of discarding some outliers values), we could see that the longest movie duration was from France. The smallest movie durations are from UK and Indian



### Question 2.10

---

❓ How does the distribution of the average vote differ based on the genre? Elaborate.

In [31]:
# Your code here
sns.set_style("whitegrid")
sns.catplot(data=imdb_filtered, x='genre', y='avg_vote', kind="box")

plt.show()


Based on this plot, we can see that
- the average vote  of Drama are more concentrated around the median (we have the small height of colored box)
- the average vote  of other three genres has bigger dispersion/variability comparing with the median value (we have the biggest height of the colored boxes)

- Drama has the biggest average vote median, and in the opposite way, Horror has the lowest avg_vote median.

### Question 2.11

---

❓How many movies have no data regarding their budget (i.e. the budget is NaN)? Store the result in a variable called **total_movies_without_budget**.

In [32]:
# Your code here
total_movies_without_budget=imdb_filtered["budget"].isnull().sum()
total_movies_without_budget

7548

### Question 2.12

---

❓ What is the % of movies that have no data regarding their budget? 

**Hint:** Remember that you have created the *total_movie_number* and *total_movies_without_budget* variables in previous questions! 

In [71]:
# Your code here

total_movies_without_budget/total_movie_number*100

print("The percentage of movies that have no data regarding their budget is {:,.2f}%.".format(total_movies_without_budget/total_movie_number*100))

The percentage of movies that have no data regarding their budget is 74.93%.


### Question 2.13

---

❓ Since the sample size of movies with budget information is still big, we can select only movies with information regarding their budget to conduct some exploratory analysis based on this data. 

Create a new dataframe called **movies_with_budget** which contains only movies with information regarding their budget.

**Hint:** To find movies in which the data regarding their budget is **NOT** NaN you might apply the <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.notnull.html"><code>pandas.DataFrame.notnull()</code></a>  method, which is the opposite of the <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html"><code>pandas.DataFrame.isnull()</code></a> method.

In [76]:
# Your code here
movies_with_budget=imdb_filtered.copy()[imdb_filtered["budget"].notnull()]
movies_with_budget.head()

imdb_title_id              original_title  year   genre  duration country  \
34     tt0004181          Judith of Bethulia  1914   Drama        61     USA   
38     tt0004681   Tess of the Storm Country  1914   Drama        80     USA   
39     tt0004707  Tillie's Punctured Romance  1914  Comedy        82     USA   
48     tt0005060                      Carmen  1915   Drama        59     USA   
52     tt0005402           The Golden Chance  1915   Drama        74     USA   

         language                       director  \
34        English                  D.W. Griffith   
38        English                Edwin S. Porter   
39  None, English  Mack Sennett, Charles Bennett   
48        English               Cecil B. DeMille   
52        English               Cecil B. DeMille   

                     production_company  avg_vote  votes   budget  
34                     Biograph Company       6.1   1239  $ 40000  
38          Famous Players Film Company       6.1    178  $ 10000  
39                Keystone Film Company       6.3   3250  $ 50000  
48  Jesse L. Lasky Feature Play Company       6.4    894  $ 23430  
52  Jesse L. Lasky Feature Play Company       6.4    187  $ 18711

At the moment the **budget** column is a string. To conduct EDA related to the budget it is necessary to convert this variable into a float. Also, for comparison purposes we need to select only movies that have the same currency type. 

Run the following code to filter only movies for which the budget is in USD ($): 

In [96]:
movies_with_budget["budget_in_usd"]=movies_with_budget["budget"].apply(lambda row: row[0]=="$") 
# creates a column "budget_in_usd" with information on whether budget is in USD

movies_with_budget_in_usd = movies_with_budget.copy()[movies_with_budget["budget_in_usd"] == True]
# creates a dataframe "movies_with_budget_in_usd" with movies for which the budget is in USD 
#added .copy() to avoid the warning in the next lines of code

Run the following code to transform the **budget** column from a string to a float:

In [97]:
movies_with_budget_in_usd["budget"] = movies_with_budget_in_usd["budget"].apply(lambda row: row[1:])
# iterates over all values of the budget column and removes the 3 first character that always stand for the EUR code

movies_with_budget_in_usd["budget"] = movies_with_budget_in_usd["budget"].astype('float')
# converts all values within the budget column from string to float

In [98]:
# in previous comments we have that we will remove the 3 first character that always stand for the EUR code
#however inside the lambda function we have row[1:]
#checking bellow the values, looks to be ok to continue
movies_with_budget_in_usd["budget"]

34         40000.0
38         10000.0
39         50000.0
48         23430.0
52         18711.0
           ...    
85496    1500000.0
85545      15000.0
85596     500000.0
85618      95000.0
85812     500000.0
Name: budget, Length: 2062, dtype: float64

### Question 2.14



❓ How is the relationship between the columns `budget` and `avg_vote`? Elaborate. 

**Don't forget that you should use the *movies_with_budget_in_usd* DataFrame for this exercise!**


**Hint:** Use [`seaborn.lmplot`](https://seaborn.pydata.org/generated/seaborn.lmplot.html) to graphically read a linear correlation between two columns:

In [101]:
# Your code here
sns.lmplot(y="budget", x="avg_vote", data=movies_with_budget_in_usd)
plt.show()


Checking this plot,budget and avg_vote are positively linear correlated until avg_vote lower than 8 budgets lower than 15 000 000$. This is not a strong correlation, but within these intervals in the most majority of situations we can see that when the budget increase the avg_vote also increase. 

Otherwise, we can see that even we have big amount of budget budget (>15000kusd) the average votes didn't increase (we can see that for bigger values of budget the average votes is around 6 (in scale 0 to 10).

For avg_votes bigger than 8, we don't identify correlation of this average votes with budget

In [102]:
#Checking the Pearson'r we can see the correlation between variables.
#the correlation is much stronger as much proxime than 1 is r.
movies_with_budget_in_usd.corr()

duration  avg_vote     votes    budget  budget_in_usd
duration       1.000000  0.348202  0.235512  0.294813            NaN
avg_vote       0.348202  1.000000  0.254510  0.186250            NaN
votes          0.235512  0.254510  1.000000  0.341393            NaN
budget         0.294813  0.186250  0.341393  1.000000            NaN
budget_in_usd       NaN       NaN       NaN       NaN            NaN

### Question 2.15

❓ Now it is time for you to show us your creativity. Find some other relevant question that can be answered with data from the **imdb_filtered** DataFrame and develop a response for this question! 


In [180]:
# Your code here
# We will decide to check some question related with column Year: 
#1. What was the evolution of quantity of films through the time?
#2. Is there any correlation between the "Year" and "avg_votes"?
#3. Is there more votes for the most recent movies?

#4. What is the movies distribution by genre?
#even this last topic is not related with time column, we think this is an interesting statistic to see 
#(before we only checked the distribution of genre by country)

In [117]:
# First,as we saw year column is not in numerical format type, so we will start for this step
# let us to check the unique values to see if there are different formats or if all has 4 digits:
imdb_filtered["year"].unique()

array([1914, 1915, 1916, 1917, 1918, 1919, 1920, 1924, 1921, 1922, 1923,
       1925, 1926, 1927, 1928, 1929, 1932, 1930, 1931, 1933, 1934, 1935,
       1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946,
       1947, 1948, 1949, 1950, 1951, 1962, 1953, 1952, 1955, 1954, 1956,
       1957, 1958, 1959, 1961, 1960, 1963, 1971, 1964, 1965, 1966, 1968,
       1967, 1969, 1973, 1970, 1989, 1972, 1975, 1974, 1977, 1978, 1976,
       1979, 1980, 1981, 1983, 1984, 1982, 1987, 1985, 1986, 1988, 1990,
       1991, 1992, 1995, 1993, 1994, 1996, 1997, 1999, 1998, 2005, 2000,
       2007, 2001, 2002, 2003, 2004, 2006, 2012, 2017, 2008, 2010, 2018,
       2011, 2009, 2013, 2019, 2015, 2016, 2014, 2020])

In [118]:
#Now we will convert year column in datetime type:
imdb_filtered["year"]=pd.to_datetime(imdb_filtered["year"], format="%Y").dt.year 
#in this case we only have year so we could have converted directly to int, anyway we can use this way if we have complete dates

In [114]:
imdb_filtered.head(3)

imdb_title_id         original_title  year   genre  duration country  \
17     tt0003167       Home, Sweet Home  1914   Drama        55     USA   
28     tt0003973  A Florida Enchantment  1914  Comedy        63     USA   
32     tt0004134             Hypocrites  1915   Drama        54     USA   

   language       director               production_company  avg_vote  votes  \
17  English  D.W. Griffith  Majestic Motion Picture Company       5.8    187   
28  English    Sidney Drew     Vitagraph Company of America       5.8    202   
32  English     Lois Weber      Hobart Bosworth Productions       6.6    456   

   budget  
17    NaN  
28    NaN  
32    NaN

In [132]:
imdb_filtered["year"].value_counts()

2018    482
2019    437
2017    423
2016    382
2014    341
       ... 
1914      6
1922      6
1923      6
1916      5
1917      4
Name: year, Length: 107, dtype: int64

####  2.15.1 - What was the evolution of quantity of films through the time?

In [128]:
# to reply to the first question we can easily to plot a histogram that shows the frequency 
plt.hist(imdb_filtered["year"]) # by default it split our dataset in 10 intervals
plt.show()

In [133]:
#or if we want to use seaborn we can plot (we expect same kind of results):
sns.histplot(imdb_filtered['year'],  kde=True, stat="density", linewidth=0)
plt.show()

In [138]:
imdb_filtered["year"].value_counts(bins=10).sort_index()

(1913.893, 1924.6]      86
(1924.6, 1935.2]       331
(1935.2, 1945.8]       318
(1945.8, 1956.4]       449
(1956.4, 1967.0]       610
(1967.0, 1977.6]       698
(1977.6, 1988.2]       842
(1988.2, 1998.8]       916
(1998.8, 2009.4]      2076
(2009.4, 2020.0]      3748
Name: year, dtype: int64

We can see a left skewed distribution, wich  means in the last years we have much more movies than before.
Checking values, we can see, we have more movies in the last 20 year, than during all century XX.

This results are according to our expectation, because even thought we know that the first cinema machines were created in 1891-1895, during first years of century XX the technology still suffered great periods of improvement. Only after years 80s it sparked a boom in out-of-town multiplex cinemas.

According to what we can read [here](https://www.scienceandmediamuseum.org.uk/objects-and-stories/very-short-history-of-cinema)"In the past 20 years, film production has been profoundly altered by the impact of rapidly improving digital technology. Most mainstream productions are now shot on digital formats with subsequent processes, such as editing and special effects, undertaken on computers.", so, this can explain the boom we see in the numbers and graphics which we plot before.

####  2.15.2 - There is any correlation between the "Year" and "avg_votes"?


In [147]:
#let us we checked the relation between data ploting a scatter plot:
with sns.axes_style(style="whitegrid"):
    sns.relplot(x="year", y="avg_vote", data=imdb_filtered)

There is not correlation between the average vote and the years.
Anyway this plot gives us an interest conclusion, based on this graphic we can see that the majority of the oldest movies (made before 60s) has average vote above 5.
The movies with worse average votes made after 60s.

####  2.15.3 - There is more votes for the most recent movies?

In [165]:
imdb_filtered[imdb_filtered["votes"]>10000].shape[0]/imdb_filtered.shape[0]*100

4.198927933293628

In [164]:
with sns.axes_style(style="whitegrid"):
    sns.relplot(x="year", y="votes", data=imdb_filtered[imdb_filtered["votes"]<10000]) #slice some outliers 

Attending IMDb platform is relatively recent (created in 1990), we would like to check if we only have votes for the most recent movies or if the oldest movies also had received a similar number of votes.

After checked this plot, we can see that independently of date of creation of IMDb, we have big number of votes for the movies made before 1990. 

Despite, it is also evident that we have more recent films with more number of votes.

#### what is the movies distribution by genre?

In [203]:
imdb_filtered["genre"].value_counts().plot(kind="pie", 
                                           autopct='%1.0f%%',
                                           textprops={'fontsize': 16, "weight":"bold",'color':"w" },
                                           legend=True,
                                           shadow=True,
                                           radius=1.2,
                                           pctdistance=0.8,
                                          )
plt.legend(loc="upper left", fontsize= 18,  bbox_to_anchor=(1.1, 0, 0, 0.9))
plt.title("Movies distribution by genre", fontsize=20)   
plt.show()

## Question 3 - Web Scraping

Let's test your Web Scraping skills!  

Start by getting the HTML from the Books to Scrape webpage parsed by running the two following cells:

In [204]:
import requests
from bs4 import BeautifulSoup

In [205]:
url = "http://books.toscrape.com/" # define the URL of the webpage we want to parse
response = requests.get(url) # request HTML  
html = response.content # get HTML as text
scraped = BeautifulSoup(html,'html.parser') # parse HTML

### Question 3.1

❓ Get the title of webpage scraped above. Only get the text within the title element and do not forget to clean any invisible characters that it might contain!

**Hint:** Remember that the HTML of this webpage has been parsed into the variable **scraped**!

In [208]:
# Your code here

title_text=scraped.title.text.strip()
title_text

'All products | Books to Scrape - Sandbox'

### Question 3.2

❓ Show us what you have learned until now and scrape a content of your choice from the Books to Scrape webpage.

In [230]:
# Your code here
#1 -  we will collect the list of category of books
#2 - we will collect the list with all book titles presented in first page



['Travel',
 'Mystery',
 'Historical Fiction',
 'Sequential Art',
 'Classics',
 'Philosophy',
 'Romance',
 'Womens Fiction',
 'Fiction',
 'Childrens',
 'Religion',
 'Nonfiction',
 'Music',
 'Default',
 'Science Fiction',
 'Sports and Games',
 'Add a comment',
 'Fantasy',
 'New Adult',
 'Young Adult',
 'Science',
 'Poetry',
 'Paranormal',
 'Art',
 'Psychology',
 'Autobiography',
 'Parenting',
 'Adult Fiction',
 'Humor',
 'Horror',
 'History',
 'Food and Drink',
 'Christian Fiction',
 'Business',
 'Biography',
 'Thriller',
 'Contemporary',
 'Spirituality',
 'Academic',
 'Self Help',
 'Historical',
 'Christian',
 'Suspense',
 'Short Stories',
 'Novels',
 'Health',
 'Politics',
 'Cultural',
 'Erotica',
 'Crime']

<table>
    <tr><img src="book category.png"> </tr>
    <tr><img src="book titles.png"></tr>
</table>

In [ ]:
# collect all books category in the sidebar:
list_categories_html=scraped.select(".nav-list li ul li a")
list_categories_html

#checking example for the first element
list_categories_html[0].text.strip()

#create an empty list to save the list the of the categories
list_categories=[]

for each in list_categories_html:
    list_categories.append(each.text.strip())

#check the result of our scrapping:
list_categories

In [257]:
#the list of all titles in the first page:

product_pod_list=scraped.find_all("article","product_pod")

#checking for first result
product_pod_list[0].h3.a["title"]

'A Light in the Attic'

In [259]:
#abstracting for all books in the first page:
product_first_page=[]
for each in product_pod_list:
    product_first_page.append(each.h3.a["title"])
print(product_first_page)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]


In [260]:
import json
print(json.dumps(product_first_page, indent=4))

[
    "A Light in the Attic",
    "Tipping the Velvet",
    "Soumission",
    "Sharp Objects",
    "Sapiens: A Brief History of Humankind",
    "The Requiem Red",
    "The Dirty Little Secrets of Getting Your Dream Job",
    "The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull",
    "The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics",
    "The Black Maria",
    "Starving Hearts (Triangular Trade Trilogy, #1)",
    "Shakespeare's Sonnets",
    "Set Me Free",
    "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
    "Rip it Up and Start Again",
    "Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991",
    "Olio",
    "Mesaerion: The Best Science Fiction Stories 1800-1849",
    "Libertarianism for Beginners",
    "It's Only the Himalayas"
]
